/**
 * 扫描 dialogs / sidepages，生成 name -> () => import(path) 注册表。
 * 启动时不再 eager 解析整站弹窗/侧栏依赖树。
 */
import fs from 'fs'
import path from 'path'
import type { Plugin } from 'vite'

const DIALOG_ID = 'virtual:dialog-registry'
const SIDEPAGE_ID = 'virtual:sidepage-registry'
const RESOLVED_DIALOG = '\0' + DIALOG_ID
const RESOLVED_SIDEPAGE = '\0' + SIDEPAGE_ID

function walk (dir: string, pred: (file: string) => boolean, acc: string[] = []): string[] {
  if (!fs.existsSync(dir)) return acc
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name)
    if (entry.isDirectory()) {
      walk(full, pred, acc)
    } else if (pred(full)) {
      acc.push(full)
    }
  }
  return acc
}

function extractComponentName (content: string): string | null {
  const patterns = [
    /export\s+default\s+\{[\s\S]*?\bname:\s*['"]([^'"]+)['"]/,
    /(?:^|\n)\s*name:\s*['"]([^'"]+)['"]/,
  ]
  for (const re of patterns) {
    const m = content.match(re)
    if (m) return m[1]
  }
  return null
}

function toProjectImport (root: string, file: string): string {
  const rel = path.relative(root, file).replace(/\\/g, '/')
  return '/' + rel
}

function collectDialogFiles (root: string): string[] {
  const isDialog = (file: string) => {
    const n = file.replace(/\\/g, '/')
    return (
      /\/dialogs\/[^/]+\.(vue|js|jsx)$/.test(n) ||
      /\/Dialogs\/[^/]+\.(vue|js|jsx)$/.test(n) ||
      /\/sections\/DialogManager\/components\/[^/]+\.(vue|js|jsx)$/.test(n)
    )
  }
  return [
    ...walk(path.join(root, 'containers'), isDialog),
    ...walk(path.join(root, 'scope'), isDialog),
    ...walk(path.join(root, 'src', 'views'), isDialog),
    ...walk(path.join(root, 'src', 'sections', 'DialogManager', 'components'), isDialog),
  ]
}

function collectSidepageFiles (root: string): string[] {
  const isSidepage = (file: string) => {
    const n = file.replace(/\\/g, '/')
    return (
      /\/sidepage\/index\.(vue|js|jsx)$/.test(n) ||
      /\/sections\/SidePageManager\/components\/.+\/index\.(vue|js|jsx)$/.test(n)
    )
  }
  return [
    ...walk(path.join(root, 'containers'), isSidepage),
    ...walk(path.join(root, 'scope'), isSidepage),
    ...walk(path.join(root, 'src', 'views'), isSidepage),
    ...walk(path.join(root, 'src', 'sections', 'SidePageManager', 'components'), isSidepage),
  ]
}

function buildRegistryModule (root: string, files: string[]): string {
  const map = new Map<string, string>()
  for (const file of files) {
    let content = ''
    try {
      content = fs.readFileSync(file, 'utf8')
    } catch {
      continue
    }
    const name = extractComponentName(content)
    if (!name) continue
    map.set(name, toProjectImport(root, file))
  }
  const lines = [...map.entries()].map(
    ([name, importPath]) => `  ${JSON.stringify(name)}: () => import(${JSON.stringify(importPath)})`,
  )
  return `/* auto-generated by vite-plugin-lazy-registry */\nexport default {\n${lines.join(',\n')}\n}\n`
}

export default function lazyRegistryPlugin (root: string): Plugin {
  let dialogCode = ''
  let sidepageCode = ''

  const regenerate = () => {
    dialogCode = buildRegistryModule(root, collectDialogFiles(root))
    sidepageCode = buildRegistryModule(root, collectSidepageFiles(root))
  }

  return {
    name: 'vite-plugin-lazy-registry',
    buildStart () {
      regenerate()
    },
    configureServer () {
      regenerate()
    },
    resolveId (id) {
      if (id === DIALOG_ID) return RESOLVED_DIALOG
      if (id === SIDEPAGE_ID) return RESOLVED_SIDEPAGE
      return null
    },
    load (id) {
      if (id === RESOLVED_DIALOG) {
        if (!dialogCode) regenerate()
        return dialogCode
      }
      if (id === RESOLVED_SIDEPAGE) {
        if (!sidepageCode) regenerate()
        return sidepageCode
      }
      return null
    },
    handleHotUpdate ({ file, server }) {
      const n = file.replace(/\\/g, '/')
      if (
        !n.includes('/dialogs/') &&
        !n.includes('/Dialogs/') &&
        !n.includes('/sidepage/') &&
        !n.includes('/DialogManager/components/') &&
        !n.includes('/SidePageManager/components/')
      ) {
        return
      }
      regenerate()
      const mods = [
        server.moduleGraph.getModuleById(RESOLVED_DIALOG),
        server.moduleGraph.getModuleById(RESOLVED_SIDEPAGE),
      ].filter(Boolean)
      if (mods.length) {
        return mods as any
      }
    },
  }
}
